### ISSUE TITLE
Error: Value for Argument 'documentPath' is not a valid resource path. Path must be a non-empty string

### ISSUE THREAD

**Issue by pdhoward** [leerob/fastfeedback#22]
I subscribed to and am following your course React2025. Excellent course! Much appreciated.

I have successfully coded along with you up to Unit 10 ... and decided to fork your project and run the completed app.

I updated the env,local with my keys. When I start the app, the error noted above is encountered in

db-admin.js Line 34
const doc = await db.collection('sites').doc(siteId).get();

The value of site-id is undefined.

It is not clear to me why the app is even retrieving any sites during startup.

Any guidance would on best way to stand up this app ... I am interested in testing it locally and studying the completed code on the Stripe integration in particular

Thanks You!

**Comment by leerob** [comment]
I'm not sure you'll be able to run the app locally without setting up your own Firebase instance with the Stripe Firestore extension. Are you saying you've already done that?

Anyways – the reason that is failing is because it's trying to fetch the Fast Feedback site (given that site ID) to display the feedback on the home route. You'll need to disable or remove that code (or change the ID to your own site).

**Comment by leerob** [comment]
Glad you're enjoying the course! ❤️

**Comment by pdhoward** [comment]
Makes sense .... Thanks much!
